"""Official Doubao AST protobuf bindings, downloaded from the official API demo.

Source: https://docs.volcengine.com/docs/DoubaoVoice/SimultaneousInterpretation20APIAccessDocumentation?lang=zh
Archive: ast-client.zip (2026-10-09). Only imports changed to package relative.
Generated by protoc 6.31.1; do not hand-edit serialized descriptors.
"""
